---
category:
  - web
tag:
  - vue
---

# hook event

> Hook Event 是 Vue 的自定义事件结合生命周期钩子实现的一种从组件外部为组件注入额外生命周期方法的功能。

```js
// 关联：_hasHookEvent, _events
// src/core/instance/events.js
const hookRE = /^hook:/

if (hookRE.test(event)) {
  vm._hasHookEvent = true
}
// src/core/instance/lifecycle.js
if (vm._hasHookEvent) {
  vm.$emit('hook:' + hook)
}
```

## use

```html
<comp @hook: [lifecycleName]="method" />
```

## sence

> 从外部注入对应子组件的HookEvent，在指定的生命周期执行时间点执行相关的外部逻辑

```html
<el-select ref="select" @hook:mounted="callback"></el-select>
```

```js
// 获取select实例注册
this.$refs['select'].$on('hook:mounted', function() {})
```

## source

### callHook

> 通过callHook方法执行相关生命周期

```ts
// src/core/instance/lifecycle.js

/**
 * callHook(vm, 'mounted')
 * 执行实例指定的生命周期钩子函数
 * 如果实例设置有对应的 Hook Event，比如：<comp @hook:mounted="method" />，执行完生命周期函数之后，触发该事件的执行
 * @param {*} vm 组件实例
 * @param {*} hook 生命周期钩子函数
 */
export function callHook (vm: Component, hook: string) {
  // 在执行生命周期钩子函数期间禁止依赖收集
  // #7573 disable dep collection when invoking lifecycle hooks
  pushTarget()
  // 从实例配置对象中获取指定钩子函数，比如 mounted
  const handlers = vm.$options[hook]
  // mounted hook
  const info = `${hook} hook`
  if (handlers) {
    // 通过 invokeWithErrorHandler 执行生命周期钩子
    for (let i = 0, j = handlers.length; i < j; i++) {
      invokeWithErrorHandling(handlers[i], vm, null, vm, info)
    }
  }
  // Hook Event，如果设置了 Hook Event，比如 <comp @hook:mounted="method" />，则通过 $emit 触发该事件
  // vm._hasHookEvent 标识组件是否有 hook event，这是在 vm.$on 中处理组件自定义事件时设置的
  if (vm._hasHookEvent) {
    // vm.$emit('hook:mounted')
    vm.$emit('hook:' + hook)
  }
  // 关闭依赖收集
  popTarget()
}
```

::: tip vm.$options[hook]

[merge options](../mergeOptions/mergeHook.md)

:::

### invokeWithErrorHandling

> 带有错误处理功能的调用

```ts
// src/core/util/error.js

/**
 * 通用函数，执行指定函数 handler
 * 传递进来的函数会被用 try catch 包裹，进行异常捕获处理
 */
export function invokeWithErrorHandling (
  handler: Function,
  context: any,
  args: null | any[],
  vm: any,
  info: string
) {
  let res
  try {
    // 执行传递进来的函数 handler，并将执行结果返回
    res = args ? handler.apply(context, args) : handler.call(context)
    if (res && !res._isVue && isPromise(res) && !res._handled) {
      res.catch(e => handleError(e, vm, info + ` (Promise/async)`))
      // issue #9511
      // avoid catch triggering multiple times when nested calls
      res._handled = true
    }
  } catch (e) {
    handleError(e, vm, info)
  }
  return res
}
```